apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ephemeplay.fullname" . }}-secret
type: Opaque
stringData:
  PLAYER_JWT_SECRET: {{ .Values.secrets.playerJwtSecret | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  REDIS_URL: {{ printf "redis://:%s@%s:6379" .Values.secrets.redisPassword (include "ephemeplay.redisHost" .) | quote }}
