apiVersion: v1
kind: Service
metadata:
  name: {{ include "ephemeplay.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "ephemeplay.name" . }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: {{ include "ephemeplay.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.port | int }}
      targetPort: {{ .Values.service.port | int }}
